version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "super123"
      MYSQL_DATABASE: "aquiline"
    ports:
      - "3306:3306"
    volumes:
      - .:/var/lib/mysql

  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/app
    depends_on:
      - mysql
